version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - fargozhu
  labels:
  - dependencies
  ignore:
  - dependency-name: ex_doc
    versions:
    - 0.23.0
    - 0.24.0
    - 0.24.1
  - dependency-name: mox
    versions:
    - 1.0.0
  - dependency-name: plug_cowboy
    versions:
    - 2.4.1
