name: Elixir CI

on: 
  push:
    branches:
      - 'deployment'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: OTP ${{ matrix.otp }} | Elixir ${{ matrix.elixir }} | OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        otp: [22.x]
        elixir: [1.9.x]

    #container:
    #  image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-elixir@v1.0.0
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
      env:
        MIX_ENV: test
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_AUTH_TOKEN: ${{ secrets.JIRA_AUTH_TOKEN }}
        SECRET_TOKEN: $$ { secrets.SECRET_TOKEN }}      
    - name: Run Tests
      run: |
        mix compile
        mix format --check-formatted
        mix test
      env:
        MIX_ENV: test
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_AUTH_TOKEN: ${{ secrets.JIRA_AUTH_TOKEN }}
        SECRET_TOKEN: $$ { secrets.SECRET_TOKEN }}